name: build
on: { workflow_dispatch, push: { branches: [main] }, pull_request, merge_group: { types: [checks_requested] } }
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
    name: nix (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-trusted-public-keys = magic-school-ai.cachix.org-1:EcAHj+Bu7cr7tnrIXr4W2hiSQMOvswmV/o8Qi9shmFQ= cache.g7c.us:dSWpE2B5zK/Fahd7npIQWM4izRnVL+a4LiCAnrjdoFY=
            extra-substituters = https://magic-school-ai.cachix.org https://cache.g7c.us
      - uses: cachix/cachix-action@master
        if: github.ref == 'refs/heads/main' || contains(github.ref, 'updates-nix')
        with:
          name: magic-school-ai
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix --show-trace build .#magicschool
